# Generated by Django 5.2.8 on 2025-12-12 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_systemservice_globalnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationUserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('is_cleared', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='portal.globalnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_user_status',
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
