# Generated by Django 5.2.8 on 2025-12-13 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_notificationuserstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='compromisso',
            name='user_id',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compromissos', to=settings.AUTH_USER_MODEL),
        ),
    ]
